# include: package:very_good_analysis/analysis_options.yaml



# analyzer:
#   exclude:
#     - "/*.gen.dart"
#     - "bin/cache/**"
#     - "test/.test_coverage.dart"
  
# linter:
#   rules:
#     sort_pub_dependencies : false